import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :kachingko_api, KachingkoApiWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

config :kachingko_api,
  # 30 days for dev
  web_token_ttl: 30 * 24 * 3600

config :kachingko_api, KachingkoApiWeb.Guardian,
  issuer: "cc_spending_api",
  secret_key: System.get_env("GUARDIAN_SECRET_KEY")

config :guardian, Guardian.DB,
  # Add your repository module
  repo: KachingkoApi.Repo,
  # default
  schema_name: "guardian_tokens",
  # store all token types if not set
  # token_types: ["refresh_token"],
  # default: 60 minutes
  sweep_interval: 60

config :kachingko_api, KachingkoApi.Vault, []

config :kachingko_api, :supported_banks, [
  "eastwest",
  "rcbc"
]
